# RuboCop configuration for stomp_base gem

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'spec/rails_demo/**/*'
    - 'spec/rails_demo_api/**/*'
    - 'vendor/**/*'
    - '**/vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

require:
  - rubocop-rspec

plugins:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rake

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'lib/tasks/**/*.rake'
    - '*.gemspec'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/ClassVars:
  Enabled: false

# Disable global variables rule for test files that need it
Style/GlobalVars:
  Exclude:
    - 'spec/unit/console_session_spec.rb'
    - 'spec/unit/console_terminal_spec.rb'

# RSpec specific  
RSpec/ExampleLength:
  Max: 40

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false
