blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/YOUR_USERNAME/stomp_base/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/YOUR_USERNAME/stomp_base#readme
    about: Read the full documentation and API reference
